package tw.gov.cdc.exposurenotifications.keydownload;

import androidx.annotation.Nullable;

import java.io.File;

// Generated by com.google.auto.value.processor.AutoValueProcessor
final class AutoValue_KeyFile extends KeyFile {

    private final String indexEntry;

    private final File file;

    private final boolean isMostRecent;

    AutoValue_KeyFile(
            String indexEntry,
            @Nullable File file,
            boolean isMostRecent) {
        if (indexEntry == null) {
            throw new NullPointerException("Null indexEntry");
        }
        this.indexEntry = indexEntry;
        this.file = file;
        this.isMostRecent = isMostRecent;
    }

    @Override
    public String indexEntry() {
        return indexEntry;
    }

    @Nullable
    @Override
    public File file() {
        return file;
    }

    @Override
    public boolean isMostRecent() {
        return isMostRecent;
    }

    @Override
    public String toString() {
        return "KeyFile{"
                + "indexEntry=" + indexEntry + ", "
                + "file=" + file + ", "
                + "isMostRecent=" + isMostRecent
                + "}";
    }

    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        }
        if (o instanceof KeyFile) {
            KeyFile that = (KeyFile) o;
            return this.indexEntry.equals(that.indexEntry())
                    && (this.file == null ? that.file() == null : this.file.equals(that.file()))
                    && this.isMostRecent == that.isMostRecent();
        }
        return false;
    }

    @Override
    public int hashCode() {
        int h$ = 1;
        h$ *= 1000003;
        h$ ^= indexEntry.hashCode();
        h$ *= 1000003;
        h$ ^= (file == null) ? 0 : file.hashCode();
        h$ *= 1000003;
        h$ ^= isMostRecent ? 1231 : 1237;
        return h$;
    }

}
